{% set version = "0.4.3" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 76c02ba5c0f417e14153ffa98004190d20bc1c526f7b5c43e2237fb649940e3c

  #git_url: https://dmiron@bitbucket.org/gems4/thermofun.git
  #git_rev: test-17

  #git_url: https://github.com/thermohub/thermofun.git
  #git_rev: master

build:
  number: 0
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: true  # [win and vc<14]
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - nlohmann_json >=3.7.0
    - python
    - chemicalfun >=0.1.7
#    - spdlog =1.10.0
#    - setuptools =59.7.0
    - pybind11-abi
  run:
    - python
#    - spdlog =1.10.0
    - chemicalfun >=0.1.7
    - nlohmann_json >=3.7.0
test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
