{% set version = "0.1.11" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 28328a6c90599d1aa7ab318e17b643c824b00c37d1acd8685e55268a5b5640b4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.13
    - ninja

  host:
    - boost
    - pybind11>=2.3.0
    - nlohmann_json>=3.6.1

  run:
    - boost
    - python

test:
  files:
    - test/

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
