{% set version = "0.3.2" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 8b3b094d1dacfcb5c03927d4041ec54e4e14e655368eb001b8b7c11b89375632

build:
  number: 0
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: true  # [win and vc<14]
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11
    - nlohmann_json >=3.7.0
    - numpy
    - python
  run:
    - python
test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
