{% set version = "0.3.9" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 49995b3a139e7ed93d2bf6ab09a316459bca809cf3f612878c9fa017befaf913

  #git_url: https://github.com/thermohub/thermofun.git
  #git_rev: master

build:
  number: 0
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: true  # [win and vc<14]
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11
    - nlohmann_json >=3.7.0
    - python
    - chemicalfun
  run:
    - python
    - chemicalfun
    - nlohmann_json >=3.7.0
test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
