{% set version = "0.2.1" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: f1be650ed512811ad2cd925a59888c7948387ac78c7bfbe1d16e973e4a6447ab

build:
  number: 1
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: True  # [win and vc<14]
requirements:
  build:
    - cmake >=3.13
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 =2.3.0
    - nlohmann_json >=3.7.0
    - numpy 1.14.*
    - python
  run:
    - python
test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
