{% set version = "0.5.3" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: c1245772cd5b3e98eccfe6cc5b2c9a22dfd3ee94a3549d28d107f51f8ec20777

  #git_url: https://dmiron@bitbucket.org/gems4/thermofun.git
  #git_rev: test-17

  #git_url: https://github.com/thermohub/thermofun.git
  #git_rev: gdmiron-patch-1

build:
  number: 0
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']
  skip: true  # [win and vc<14]
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - pybind11
    - nlohmann_json >=3.7.0
    - python
    - pip
    - setuptools
    - chemicalfun >=0.1.9
    - spdlog
#    - setuptools =59.7.0
    - pybind11-abi
  run:
    - python
    - chemicalfun >=0.1.9
    - nlohmann_json >=3.7.0
test:
  imports:
    - thermofun

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
    - sdmytrievs
