travis:
  secure:
    BINSTAR_TOKEN: SErYe9FllBYV/L7EgL68X5+nM07vOxPeujarvN22O+Eidllajm/52L4+QtPUWfESAOUWdmFSUXJhgWvjeO2p0MqFWR/H24Lh9HuVzyJR/uqVaQJNXykvPYrwtL813Wg03pttuGw90GXPCyYx2uvRBPZKuA1nd55g2CSxlGOsYq7gONBDBVUZ95HrWZMdQdtYosmyH6FEp8N70Zuj+wM6s8Nrq+R+NH4xQTBq3PoZFXzaiPL2U4vMqoAkIj2cqqEzhRa+qPsh5P9PHsz7oMrLlBVIEvy2fwqgQunXKWErjd/8MSTo434vUUg0iV8R51STKtxqCwx928VvjnuZ7xzFy21XmZzZ47YPJp5M5qhi0bYsD+0FVJkrzpuX5zx9Px51+ANxnQZl6BOQKaZC7IMG0gVYj26J1rsoGhcYYtygPQrHdGeUVAVf1I2v2FMNWjf0DlwmZzhMu9cIspKeWlUA0lNYA8VFpp9vYQNa3uj4Luxfw3cs7cB8hhRpNZ7rXRrBuCNc5IYCO2PC8HfxmtSGft3/Y2KVRGurf+j7/QAvF26xoeAoJcJauI1aJAB3hnGs/HVfJ96mzwT/VUF+LUF+BjpNF0Dhp6onwi78eklsr++EiGldhQRKjAzX11LUfh3rxJOa9O6cTrkUbm/Q3UgdCpWlv2fPAJcaKnXbBGzNDVE=
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
